### ISSUE TITLE
Useful for sente

### ISSUE THREAD

**Issue by awb99** [luminus-framework/luminus-jetty#2]
It seems to me that this jetty adapter was made because jetty seems to lack a few interfaces.

Im investigating if I can add a jetty adapter for the sente websocket library. I figured that luminus-jetty should have solved this issue?

Thank you!

**Comment by yogthos** [comment]
It should be possible to make it work with Sente, but I haven't looked at that. If you'd like to give it a shot I'm open to a PR.

**Comment by awb99** [comment]
@yogthos I would love to. But I don't yet understand the jetty internals good enough.
