### ISSUE TITLE
version 0.2.0 is published but not in master

### ISSUE THREAD

**Issue by antonmos** [luminus-framework/luminus-jetty#6]
it appears it was published from the `ws` branch, which is '1 commit ahead and 9 behind master'
Also, it looks 0.2.0 ring-jetty-adapter is 1.8.0, while in master's 0.1.9 it is 1.8.1
Moreover, the published pom.xml for 0.1.9 is referencing ring-jetty-adapter 1.8.0

Is this intentional?

**Comment by yogthos** [comment]
Hi, thanks for the heads up. I've merged the ws to master and bumped up dependencies in `0.2.1`. Let me know if everything looks good.

**Comment by antonmos** [comment]
looks good!
