### ISSUE TITLE
Switch to sunng87/ring-jetty9-adapter?

### ISSUE THREAD

**Issue by sunng87** [luminus-framework/luminus-jetty#8]
As https://github.com/sunng87/ring-jetty9-adapter/issues/41 merged into master of ring-jetty9-adapter, shall we switch the jetty backend of this library to ring-jetty9-adapter completely? It provides more features and actively maintained against latest jetty upstream.

**Comment by yogthos** [comment]
Yeah that sounds like a good idea. Would you mind taking a look if the docs need to be updated if there are API differences and making a pr?

**Comment by sunng87** [comment]
Nice. Let me look into the internals.
